name: Release
on:
  release:
    types:
      - created

jobs:

  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install tsc
      run: npm install -g typescript
    - name: install dependencies
      run: npm ci
    - name: compile typescript
      run: tsc
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: npm run publish

  publish_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install tsc
      run: npm install -g typescript
    - name: install dependencies
      run: npm ci
    - name: compile typescript
      run: tsc
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: npm run publish

  publish_on_win:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 16
    - name: install tsc
      run: npm install -g typescript
    - name: install dependencies
      run: npm ci
    - name: compile typescript
      run: tsc
    - name: publish
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: npm run publish